services:
  tg-userbot:
    build: .
    platform: linux/amd64
    container_name: tg-userbot
    network_mode: host
    env_file:
      - .env
    environment:
      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}
      - TG_SESSION=${TG_SESSION}
      - TG_PHONE_NUMBER=${TG_PHONE_NUMBER}
      - TG_PASSWORD=${TG_PASSWORD}
      - TG_PHONE_CODE=${TG_PHONE_CODE}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AUTO_TRANSCRIBE_PEER_IDS=${AUTO_TRANSCRIBE_PEER_IDS:-}
      - TRANSCRIBE_DISABLED_PEER_IDS=${TRANSCRIBE_DISABLED_PEER_IDS:-}
    volumes:
      - ./voices:/app/voices
    restart: unless-stopped
